### ISSUE TITLE
Content Ideas

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#12]
- Develop ideas for what content should be on the website to answer most commonly asked questions on site and lessen the amount of emails Rob receives

**Comment by matthall8** [comment]
@Rob1Paul - can you share any insight on the most commonly received questions you get before people sign up?

**Comment by Rob1Paul** [comment]
@matthall8 Probably the most commonly asked question is a broad and general one.... How does the service work? This stems from the fact that at the moment there's no 'how it works' explainer on the site. 

Most website visitors arrive on the site via an article about the service so they have a decent sense for the experience, but they don't quite get the process/ mechanics/ practicalities... these people are wanting to know things like... What communication platform can I use? (People are conscious they may be paired with someone in another country... and are thinking about cost) How do you match people?... How do you choose the books? (rare) 

Sometimes I receive questions after sign up... I often send a copy of the Audrey Guide (in the dropbox).

At the end of the profile questionnaire the final question asks if there are any special requests. Mostly people don't write anything, but if they do, it's either about the communication platform, or a preference to be paired with someone of the same or opposite sex. 

Fielding FAQs isn't something that takes up much of my time - atleast not at the beginning of the experience. As people go deeper into the experience people often ask about book selection, has the book been abridged etc. (which I haven't been disclosing at the outset). 

That said, I don't know how many people don't proceed with sign up because they don't have a better understanding of the experience. 

When the reader and listener are approaching the end of their book together I often receive questions about what next... what are the options etc...

**Comment by matthall8** [comment]
@Rob1Paul  - Thanks Rob!

**Comment by Rob1Paul** [comment]
@matthall8 Another thought on this... Not an FAQ per se, but one of the biggest issues that comes up regularly is scheduling and reading partner commitment... so some clear guidelines/ expectations around this theme would be helpful... a proportion of people over-commit.... they like the idea... they sign-up, get paired up, and then realise it's not enough of a priortiy to make the time for it....  I don't think that it's intentional.  It just happens.

Can we find a way to reduce this. 

Having to deal with this and the re-pairing is time-consuming.

Thanks.

**Comment by matthall8** [comment]
Will be looked at as part of #26
