### ISSUE TITLE
Form updates based on user testing

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#139]
@Rob1Paul, I have noted the following form updates on the back of the user testing, please can you confirm?

* Remove location question, time zone is sufficient 
* Remove abridged books question
* Rethink how to ask for book preferences, radio buttons or checkboxes?
* Gender to be input box?
* Continue theme of 'Audrey' persona in the placeholders.

I'll be working on this this morning so let me know.

**Comment by Rob1Paul** [comment]
Yes, please remove the location question and please remove the abridging question.

The gender question is as per the copy in the dropbox folder....

Label: Check/Select one or more options that reflect your gender.
Input: woman, man, non-binary, transgender, intersex, two-spirit, gender non-conforming, prefer not to say, other (give option to type)

For the book preference question lets go with:

Label: What do you fancy reading?
Input:  Fiction Non-fiction Don't mind 

Re the Audrey persona.... I am not sure whether to create an audrey persona, or just be me, or just do something for the bio section, and have the rest with generic placeholders where applicable.

**Comment by sbinlondon** [comment]
Hi @Rob1Paul - following our phone convo, here are some thoughts:

* As I mentioned, general UI best practice is to not ask for it unless you have a valid reason. However, it sounds like you have quite a few people requesting same-gender reading partners, especially women, so if you feel that this is worth including then we will.
* Best practice guidance tells us that if we do include gender, we ought to explain why. This is supported by feedback from your users, and from people with whom we user tested last week, asking why gender is on there.
* If this is worth doing, then it's definitely worth doing sensitively and well. I believe you pulled the options from [this article](https://uxdesign.cc/designing-forms-for-gender-diversity-and-inclusion-d8194cf1f51), which I had a few UX people send to me as a good place for guidance as well. I have some thoughts re: the list and the other guidance included in this article.

1. _As with any form field, if there isn’t a clear benefit to the user, you probably shouldn’t ask about it._

You've established that it benefits some users who feel safer reading with someone who identifies as the same gender, so this gives us a reason for asking. One thing you'll need to do is write us a quick bit of copy to add to the form under this question explaining why we're asking. This will clarify to users our intentions and hopefully put them more at ease.

2. Make it optional

It shouldn't be a required form field - to me, this also means that we don't need a 'prefer not to say' option, because leaving the field blank is them preferring not to say. We should make it explicit that the field is optional, though.

3. Lists vs inputs, genders vs pronouns

The list you've put is great and I can see it's based on guidance in this article. I would say that I think it has its own faults. For example, intersex is a biological designation and shouldn't be confused with gender (i.e. someone who is not biologically XX or XY could identify as man, woman, non-binary, etc).

Including transgender as an option might be best practice for some forms for some services (i.e. medical services); however, for our purposes, I don't think it's worth including. If someone identifies as a woman, then they're a woman, whether they were assigned this at birth or not, so if someone wants to read with another woman it shouldn't matter whether they are cisgender or transgender.

Additionally, two-spirit is a very specific reference to Native American culture. There are similar genders to be found in other cultures all across the world. Including two-spirit opens the door to include many, many other options.

**My recommendation:** an open input field, explaining why we ask, and stating that it is completely optional. As it is, we have what I assume will be a drop-down list, with the option to type in if you choose 'other'. If the option to freely type in comes up at all, then I think it's best to just have this as the only option instead of mixing form inputs.

4. Safeguarding

In the end, if it all boils down to allowing people to feel safe by reading with someone of the same gender, you could possibly omit gender and if people get in touch expressing concerns about reading with someone of the opposite gender, you can ensure them that steps are taken to prevent this, and if/where concerns are raised, then are dealt with seriously. 

And then of course make sure to curate your community, listen to concerns people have if someone is acting inappropriately, and make sure to build in other forms of safeguarding to make sure this doesn't happen, as much as it is possible to do so.

--------

It's all definitely difficult and it's almost certain that no site out there deals with any of this in exactly the right way. Even if they do, someone from one side or another is likely to raise an issue. The best we can do is do what you think is best for your users, then continue iterating on the feedback they provide.

Let me know what you think - sorry for the essay! - and we're happy to continue forward with what you think is best.

**Comment by matthall8** [comment]
Hi @Rob1Paul - In addition to this, I've just updated the content on the form 3 page and it is looking quite wordy on mobile:

![image](https://user-images.githubusercontent.com/9437789/47020166-a889eb80-d150-11e8-9712-dbcf7747a4e8.png)

Is there any way we can cut this down?

**Comment by Rob1Paul** [comment]
Hi @sbinlondon thank you so much for taking the time to thoughtfully consider the gender question. 
For now, I'd like to go with your recommendation of an open input field (which is optional), but lets not have an explanation for why we ask.

You got me thinking about the age question. I thought it may be more appropriate to have bands? e.g. 

18-24
25-34
35-44
45-54
55-64
65-74
75+

**Comment by Rob1Paul** [comment]
Hi @matthall8 I have shortened the bio question and put the copy in the Dropbox creative folder. The doc is 'Sign Up - Your Story Qu - 17 Oct 2018' Hope it's an improvement. Thanks

**Comment by sbinlondon** [comment]
Thanks @Rob1Paul will change the form now with the new age and gender inputs. I agree that age bands are probably better.

**Comment by matthall8** [comment]
Sorted in PR #154
