### ISSUE TITLE
Rob's feedback 

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#169]
@matthall8 @BenNewman90 @DenisKent @sbinlondon 

Hi all! 

Desktop view feedback .... here are some of my thoughts... please call if you want me to clarify. 

Proportions on homepage - CTA too large relative to picture
Picture looks rather odd - the way the hands are cut off. 
CTA turns a deep red - can we tone down - it makes me think of 'stop'
Think the words 'Read Aloud together' should be considerably larger.... proportionally like they are on mobile.  
Wonder if we need to add more books from that shutterstock image to balance the page?

Why? is now on homepage - prefer it's not.

Would like the 'Why?' section to be a single paragraph rather than separate lines. 
Better if title is 'Our Why?' with question mark
Wonder if font should be larger/ bold for this section - and maybe in the pink colour / or grey

As seen on icons - would like them to be considerably smaller and horizontally aligned rather than vertically

CTA is Get Started - but we have 'Join Us' in top right. This needs to be consistent

'Questions' (currently called FAQs)

Can we make all the questions and answers look a bit more attractive? using our colours etc.
all black text looks out of place in the context of the feel of the rest of the site. 

Can we have it so questions and answers appear more like this:
https://www.sofarsounds.com/faq

I think we should be using a grey like the one on this site for our copy. 

I don't think Audrey Terms Privacy Contact should be spread across the page at the bottom
Think we can group Audrey Terms Privacy on one side and contact on the other. or have them all on one side. 
Also think they should be a softer and much more discreet colour

Recent reading partners no need for bullet points or full stops
Can we make this a little more friendly / attractive?

Generally - where we have the black text/ copy - I think we need to soften/ make a tad for friendly - maybe a darkish grey - not sure? - a little more like the placeholders in the contact us form.... sorry i'm repeating myself :)

Contact us form.... below the submit button... can we have that text as one paragraph rather than 3 separate lines. 

'Three steps to begin your reading adventure' - on desktop can this be horizontal/ rather than vertical as it is on mobile? With pretty arrow pointing between the steps. 

Haven't looked through form as not working at the moment.... notice colours are different though

Thank you!

**Comment by matthall8** [comment]
Thanks @Rob1Paul , we'll action.

The forms should be available on this URL: https://happy-mcnulty-44dd19.netlify.com/Form1

Let me know if you have any issues.

**Comment by Rob1Paul** [comment]
@matthall8 using that link the continue button is not working properly

also colours very different in different browsers.

**Comment by Rob1Paul** [comment]
@matthall8 

Feedback on Form:

Insert placeholders as per doc 'Sign Up Placeholders 17th Oct 2018'

Welcome to Audrey. Remove full stop

'You're warmly invited to join our community. Let's get the ball rolling... Please complete the questions below.'  Slightly larger and grey font colour

'We'll use this to introduce you to your reading partner' move to left under question wording
make more subtle - light grey

'In order to find you a reading partner we’ll need a little more information'. Make more attractive / maybe use red/pink

remove '(How rude!)'

Re word to : 'Would you rather be a Reader or a Listener?'
Option to be: Reader, Listener, Either/Both
Make answer options front grey?


Touch more space between questions....
Would you rather be a Reader or a Listener?
What do you fancy reading?

Update copy before and after your story field. see 'Sign Up - Your Story Qu - 17 Oct 2018'
copy not to be centred. 
grey text

Need tips - not in bracks or underlined. 

submit button should say 'Come on in!'

No facility to move back between the sections

**Comment by Rob1Paul** [comment]
@matthall8 
![website colour error 18 oct 2018](https://user-images.githubusercontent.com/43749507/47164649-58498f80-d2f0-11e8-9397-3d401883a71b.jpg)

@matthall8 image of website colour error attached. I can tell if I've attached correctly so also in dropbox. 
creative folder called Website Colour Error 18 Oct 2018

**Comment by Rob1Paul** [comment]
@matthall8 this is to illustrate

![website colour error ii 18 oct 2018](https://user-images.githubusercontent.com/43749507/47164958-f5a4c380-d2f0-11e8-8a03-63a6de62f243.jpg)

**Comment by sbinlondon** [comment]
_Proportions on homepage - CTA too large relative to picture
Picture looks rather odd - the way the hands are cut off.
Wonder if we need to add more books from that shutterstock image to balance the page?_

I've adjusted the desktop to hopefully look a bit better. Please let me know if you think things still feel 'off' but I hope they feel ok now.

<img width="1274" alt="screen shot 2018-10-18 at 16 14 56" src="https://user-images.githubusercontent.com/37520401/47164970-fb020e00-d2f0-11e8-858c-87ff0643ff59.png">

_CTA turns a deep red - can we tone down - it makes me think of 'stop'_

This has been changed to just be the inverse color - green buttons turn pink, pink buttons turn green.

_Think the words 'Read Aloud together' should be considerably larger.... proportionally like they are on mobile._

Updated and much larger now

_Why? is now on homepage - prefer it's not._

Removed

_Would like the 'Why?' section to be a single paragraph rather than separate lines.
Better if title is 'Our Why?' with question mark
Wonder if font should be larger/ bold for this section - and maybe in the pink colour / or grey_

Now one paragraph and changed to dark gray text, larger text.

_As seen on icons - would like them to be considerably smaller and horizontally aligned rather than vertically_

Vertical on mobile, horizontal on desktop now

_CTA is Get Started - but we have 'Join Us' in top right. This needs to be consistent_

Updated

_'Questions' (currently called FAQs)
Can we make all the questions and answers look a bit more attractive? using our colours etc.
all black text looks out of place in the context of the feel of the rest of the site._

_Can we have it so questions and answers appear more like this:
https://www.sofarsounds.com/faq_

Do you mean with drop down and hide sections?

_I think we should be using a grey like the one on this site for our copy._

Have updated some copy through the site to dark gray.

_I don't think Audrey Terms Privacy Contact should be spread across the page at the bottom
Think we can group Audrey Terms Privacy on one side and contact on the other. or have them all on one side.
Also think they should be a softer and much more discreet colour_

I have brought them all to the center. I think having three on one side vs one on the other, or all left-aligned would look unbalanced. If you still feel strongly about them not being centered now, let me know and I can change them again.

_Recent reading partners no need for bullet points or full stops
Can we make this a little more friendly / attractive?_

Bullet points removed and styled some more 👍 

Generally - where we have the black text/ copy - I think we need to soften/ make a tad for friendly - maybe a darkish grey - not sure? - a little more like the placeholders in the contact us form.... sorry i'm repeating myself :)

_Contact us form.... below the submit button... can we have that text as one paragraph rather than 3 separate lines._

Updated to one paragraph

_'Three steps to begin your reading adventure' - on desktop can this be horizontal/ rather than vertical as it is on mobile? With pretty arrow pointing between the steps._

Now horizontal on desktop like ASO section

**Comment by sbinlondon** [comment]
@Rob1Paul Can you let us know on which browser the colors are 'wrong'? This will help us troubleshoot more.

**Comment by Rob1Paul** [comment]
@sbinlondon Sorry, I'm now home and don't have access to my desktop computer - I was flicking between between chrome, firefox and internet explorer. I think it was internet explorer. I can check again in the morning.

**Comment by Rob1Paul** [comment]
@sbinlondon i've made a few comments in the text above re the changes.... mainly to do with not being able to see the changes when I visit https://happy-mcnulty-44dd19.netlify.com

**Comment by Rob1Paul** [comment]
![image](https://user-images.githubusercontent.com/43749507/47182461-6a8df280-d31d-11e8-8296-82338d8298d5.png)
@sbinlondon

**Comment by Rob1Paul** [comment]
@matthall8 @sbinlondon screenshot of problems with landing page as rendering on mobile in chrome browser...

![screenshot_mobile_chrome_18th_oct_2018](https://user-images.githubusercontent.com/43749507/47184765-78467680-d323-11e8-8092-3a177526b081.png)

**Comment by Rob1Paul** [comment]
@matthall8 rendering 3 different ways in 3 different browsers.... examples below....

Chrome

![image](https://user-images.githubusercontent.com/43749507/47207616-947a0000-d383-11e8-98ab-a0b99032141f.png)


Internet explorer

![image](https://user-images.githubusercontent.com/43749507/47207648-ab205700-d383-11e8-9095-838726fd6403.png)

Firefox

![image](https://user-images.githubusercontent.com/43749507/47207667-b83d4600-d383-11e8-80f9-72ec937115ba.png)

**Comment by matthall8** [comment]
Thanks @Rob1Paul - we are working through these :)

**Comment by Rob1Paul** [comment]
Thanks for this @matthall8 I have updated/amended ....

Navigation

•	Update FAQs to Questions
•	More padding on the right of get started
•	Get started icon to change to pink when hovered over.
•	Check ‘hand’ appears when you hover over all ‘get started’ buttons and all buttons in sign up form

Homepage

•	Home splash still not perfect on some devices. Needs more space between text and images. We will explore separate images and slightly fading images into the background.
•	Possible make images a little smaller
•	Update icons on the Three Steps – including adding right pointing arrows between the steps. 3 Icons colours to be matched to our colour scheme. 
•	Titles ‘Recent reading partners’ and ‘What our community are saying’ – make sure they are the same size.

Form

•	Remove full stops on headings.
•	Add ability to go back e.g. from step 3 to step 2, step 2 to step 1
•	Make the text on the 3 steps clearer/ larger (Contact Details etc..)
•	First Step – Remove text ‘Let's get the ball rolling...’
•	Remove 'We'll use this to introduce you to your reading partner' 
•	Update all placeholders – see dropbox doc 
•	Remove (How rude)
•	Slightly more spacing between Reader/listener question and book preference question – and shift both down a touch from time zone question
•	‘Would you rather be a Reader or a Listener?’ – Needs a question mark
•	Answers should be Reader and listener – add ‘er’ 
•	 3 options should be i Reader, ii Listener iii Don’t mind (try both)
•	Make ‘Need Tips’ more beautiful
•	Step 3 – update copy – see doc. ‘Sign Up - Your Story Qu - 17 Oct 2018’
•	Remove Go back to homepage from the thank you page
•	Remove the words ‘That’s the hard part done. Welcome to our community’. from the thank you page.
•	Is thank you page text editable by me?
•	Make social buttons work and text editable on thank you page.
•	Make social buttons our colour scheme, or at least email one. 
•	Below ‘Help Spread The Word’ heading change text to ‘Why not share the story of Audrey?’ 
•	Instead of ‘Have a great day!’ put ‘Happy reading!’

Questions page

•	Each question heading to be on left hand side (including question section titles)
•	Answers justified
•	Question and answers laid out similar to https://www.sofarsounds.com/faq  i.e. click to open answer. 

Privacy page 

•	Heading for each section to be on left, not centred
•	All headings to be the same size, so ‘definitions and interpretations’ needs to be smaller
•	Last line on privacy page ‘You may contact….’ To be the same size as other text.

Terms page

•	Heads to be same size as on privacy page (i.e. same size as heading ‘Scope of this privacy policy’). So headings should be smaller. 
•	All text should be the same size, so make text in introduction smaller, like other text.
•	
Other items discussed – more back-end

•	Change over email address – what email address (readwithaudrey@gmail.com or rob@readwithaudrey.com/ also set up support@readwithaudrey.com). TBC.
•	Make form testable / Give Rob ability to test form capture/ airtable populating. 
•	Transactional email timings set up
•	Placeholder text if social media link clicked (placeholder twitter ‘once upon a time I decided to read a book with a stranger – give it a try readwithaudrey.com’
•	Adding a transactional email ‘don’t forget to book your reading session with your partner’ (say 36 hrs after pairing.)
•	Make sure auto-generated transactional sendgrid emails appears in email outbox as verification email has been sent (important). 
•	Update transactional email headers as per dropbox file
•	Review and update copy section in transactional email ‘reader and listener allocation’ please can you send me the two versions of copy you are proposing? (Matt, think you deleted original text from dropbox doc.)
•	Check whether pair introduction transactional email will send if no attachments in the appropriate airtable field/cell. Would like this to be possible as I start to test other reading options as alternative to pdfs.
•	Sendgrid unsubscribe set-up
•	I think Denis captured most of these technical tasks – it’s possible there were one or two others.
•	All handover docs. Passwords. Migration etc.

**Comment by matthall8** [comment]
All feedback captured as separate issues or included in issue #208 .
