### ISSUE TITLE
Cross-browser compatibility

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#258]
Review design in Explorer, Firefox, Safari, and Chrome.

**Comment by BenNewman90** [comment]
@Rob1Paul can you post screenshots of the errors in explorer, please?

Also, which version of Explorer are you using?

**Comment by Rob1Paul** [comment]
@BenNewman90 Here are some screenshots I have just taken...

This is Microsoft Edge... I thought it was explorer.....

![image](https://user-images.githubusercontent.com/43749507/48226596-11533500-e398-11e8-8dea-82136bbe33f1.png)

Still issue with get started button in top right. 

I think I have been looking on explorer at work - I can send screen shot in the morning. 

Also note what happens when I shrink the window size... this doesn't seem to happen with other site... 

![image](https://user-images.githubusercontent.com/43749507/48226889-c0900c00-e398-11e8-80f8-bf37b023a57e.png)

**Comment by Rob1Paul** [comment]
Hi @BenNewman90  Good morning.... Here's are screenshots from Internet Explorer 11.....

![image](https://user-images.githubusercontent.com/43749507/48255602-21edc480-e405-11e8-889b-ac6a75745178.png)


![image](https://user-images.githubusercontent.com/43749507/48255623-3336d100-e405-11e8-8841-67e2e6a77dbb.png)

**Comment by BenNewman90** [comment]
Hi @Rob1Paul , I've updated the master so you can now see the CSS changes. The missing section is now included, padding has been added to the top right button and the text in the buttons now remain on the same line.

I've increased the opacity of the background. I think this is the best solution as turning them into separate images will cause issues. If this simple fix is satisfactory I think we should stick with it. 

Browser compatibility can be challenging. It is worth noting that less than 5% of people use Internet Explorer in the UK, and 3% globally. I will have a look at this over the weekend, however, there may not be an easy fix and could be a bit of a time sink. The problem stems from that Internet Explorer does not support some of the fairly standard tools used on our site.

I recommend that we don't use green arrows between the images as this is another component that needs to be responsive and look good on all devices (simple is better). I think it is already clear what the images mean, however, If you are sure you want them I am happy to add them.

**Comment by Rob1Paul** [comment]
Hi @BenNewman90 thanks for this and thanks for you're work on the project this week.  I'll take a look at everything over the weekend/ Monday morning and I'll feedback on Monday. I hope you have a good weekend.

**Comment by BenNewman90** [comment]
Following on from our conversation, we have agreed to put this issue on hold as it is a time sink.
