### ISSUE TITLE
Stef - light feedback and support

### ISSUE THREAD

**Issue by Rob1Paul** [ReadWithAudrey/readwithaudrey#61]
@matthall8 @sbinlondon @BenNewman90 @DenisKent Stef has kindly offered to be on hand to give you some light remote feedback and support - including code review, and helping with tech and UX decisions.

I believe we can invite him to the Github ReadWithAudrey repository, and you can action a pull request so he can review?

Please can we take advantage of this offer as I'm sure his feedback and support will be really valuable.

**Comment by sbinlondon** [comment]
Hi @Rob1Paul - we really enjoyed meeting with Stef and he gave us lots of food for thought and great advice that has directed the project already. We've already acted on a lot of it by using Gatsby (a template to start building the site on) and looking into Tachyons/Tailwind for CSS (the language used to style the website and make it look nice), and using Netlify to host our Gatsby site so that you will be able to edit some of the content easily without having to deal much with code.

We would certainly be interested in having his feedback on UX in particular as we start hammering that out in real code this week, working off our wireframes. It will be very important to get that right over the next few days so there are no big changes that need to be made next week, when it is late in the project.

However, due to the speed at which we need to work, we think it would be unfair on Stef to ask him to be on hand to code review every time we're making changes, which is several times per day. I think it would be fine to give him access to the repository so that he can have a look every once in a while in his spare time. He's more than welcome to leave comments and raise issues, and we'll respond to them as we see them. I'm sure he'll continue to have valuable insights to offer us.

**Comment by Rob1Paul** [comment]
@sbinlondon All sounds very sensible. Thank you.

**Comment by matthall8** [comment]
@Rob1Paul - please can you send us Stef's github email address and we'll add him to the repo.

**Comment by Rob1Paul** [comment]
His Github username is stefl 
Is that enough or do you also need an email?

**Comment by matthall8** [comment]
@Rob1Paul Invited him! Let me know if he didn't receive the invite.
