### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by matthall8** [ReadWithAudrey/readwithaudrey#65]
Hi @Rob1Paul - did you have any additional thoughts on fonts from what we discussed last week? We're now moving to a stage where we can begin using different fronts, as we're outside of Figma so it'd be good to decide on a font ASAP.

**Comment by Rob1Paul** [comment]
Hi @matthall8 I have been thinking a bit about fonts... Please see font ideas in the dropbox folder creative, doc called 'Font Ideas 9th Oct 2018'. In the notes it lists the fonts I'm thinking about. 
A little tricky to commit without seeing the elements together (illustration, colour, design etc.). But hopefully if we can sit and do a similar exercise to last time we should hopefully be able to get it agreed tomorrow. Will that be okay?
Welcom your thoughts on the ideas/font suggestions in the doc. 
Thanks for all your help, Rob

**Comment by matthall8** [comment]
Yep, sounds like a good course of action. We'll have a think about it ahead of tomorrow too. See you tomorrow.

**Comment by sbinlondon** [comment]
![rwa_doubleporter_montserrat_doubleporter](https://user-images.githubusercontent.com/37520401/46746560-32e0d400-cca7-11e8-9e51-bf7314a81bbd.png)
![rwa_doubleporter_montserrat](https://user-images.githubusercontent.com/37520401/46746561-32e0d400-cca7-11e8-953b-26ea8dec84cb.png)
![rwa_doubleporter](https://user-images.githubusercontent.com/37520401/46746817-c31f1900-cca7-11e8-9c04-d4b368760b6a.png)


@Rob1Paul here are some different mock ups based on our discussions this morning. I think it would be good to get @stefl's idea of what feels right as well since he's also got a good eye for design. 

This is using Double Porter for the cursive font, Montserrat in different ways for the rest of the header, and PT Serif for the rest of the text (except the one that is all cursive - that is all Double Porter).

I actually don't think it's too bad having the header all in cursive - it gives it character. But I can understand what you were saying earlier about each word having a different 'feel' to it.

**Comment by stefl** [comment]
Hi folks - I'll include this in my full feedback - see #85

**Comment by matthall8** [comment]
Closing issue as solved in person.
