### ISSUE TITLE
Feedback from Stef?

### ISSUE THREAD

**Issue by stefl** [ReadWithAudrey/readwithaudrey#69]
Hi folks,

Nice to be here. If you need me to help with anything, then do ask. I'm happy to give feedback on PRs or on issues, just tag me.

I can see you're making a lot of progress, so if you don't need me, don't feel like you have to, but I'm here if I can help.

Stef

**Comment by sbinlondon** [comment]
Hi @stefl, welcome! Thanks so much for volunteering your time.

@matthall8 and I are currently working on the front end and components. We'll aim to push up around 5 pm and then perhaps you can have a look at that and leave us feedback to go from tomorrow morning?

Not sure if @BenNewman90 or @DenisKent want to add anything - will let them do that if they want.

I'll be sure to pop a README on the repo so that you'll have everything you need to run the project.

**Comment by stefl** [comment]
Hi folks, I'll take a look this evening then!

**Comment by matthall8** [comment]
Hi @stefl - apologies, we didn't get to a point to share yesterday, we thought it'd be better to get the font sorted with Rob today before sharing as we know it will impact the site's look and feel. 

I'll let you know when a version ready for your review is on GitHub. Hopefully by the end of today.

**Comment by stefl** [comment]
I can look again this evening if you need me!
