### ISSUE TITLE
User feedback

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#79]
## Tulio
age: 20-30
profession: CPU programmer
* Join us twice on front page
* Form pages, should say next not submit
* The old website wasn’t working on mobile. His friend tried to open the document and couldn’t finish it on mobile and lost the data a few times. Getting it working on mobile would be great.
* Is it possible to get the time zone from the location?
* Likes the colours and the more fun feeling of the site

**Comment by matthall8** [comment]
# Jen

Age: 40-50
Profession: Liberian

* Very clean and clear design
* Bio is intimidating, perhaps break down into multiple tick boxes and then a small bit to add whatever you want 
* Overall it is user friendly and looks good.

# Nigel

Age: 50-60
Profession: Professor 

* Get started link is unclear, thought it would produce more information
* Had troubles clicking on the radio buttons
* Thought it'd be a good idea to add Time preferences option
* Bio is difficult to answer, do we need all that information? Perhaps "your interest" is better.

**Comment by sbinlondon** [comment]
# Armand
Age: 20s
Profession: coding student

-not sure what ’special requirements’ is on the form. placeholder text should give an example.
-viewport of 90 on the initial homepage so that you know there’s more below and you need to scroll down?
-don’t scroll all the way to the bottom for the FAQs - perhaps put a button at the bottom of the ‘about’ (second) homepage section or in the header somewhere to link to them

# Michael
Age: 30s
Profession: coding student

-clicking the book icon in the header should take me back to the homepage but it doesn’t
-gender shouldn’t be a radio button or if you choose ‘other’ then let the person specify, or just make it an input box
-didn’t know what an abridged book is - should we clarify this by saying ‘abridged (shortened)’?
-FAQs were not in the form of questions so even though I just read the FAQ page I didn’t realise it
-we have a contact form so do we also need to put Rob’s email on the site? The email can be scraped and used for spam. Also do we need to add a captcha to the form?
-things in the footer are supplementary so I didn’t think they were links I would want to visit - put important stuff like FAQs, Our Story, etc in the flow to complement a menu elsewhere
-design looks very professional
-form scroll does not reset to top of page between each section

# Jessie
Age: 20s
Profession: coding student

-likes the colours
-form scroll does not reset to top of page between each section
-also does not know what an abridged book is
-love the coral pink and green combo
-lots of links and stuff at the bottom but if I was on the homepage and wanted to do this stuff I’d have to scroll all the way to the bottom
-love the header image and how it matches the color scheme on the page

# Jolanda
Age: 30s
Profession: data scientist

-‘home’ link in footer and ‘go back to homepage’ on form are redundant
-color scheme is calming and happy
-would expect navigation at the top of the page although I’ve seen it at the bottom of the page in some places
-look at our highlight/focus/hover color on the form inputs - it doesn’t seem to match the site

# Rob
Age: 20s
Profession: UX designer

-need to check the accessibility of white text on the shades of green and pink we've chosen

**Comment by Rob1Paul** [comment]
**Lucy 30 yrs. Writer for Theatre. Entrepreneur. Has used Audrey.**  

 think when it first loads it looks really good - clean design, warm colours, really clear and nice. 

Scrolling down - at the "Register", I thought this was a CTA in order to register and tried to click it, but then realised it was just text. I think when using terminology like that, you need to allow a customer to action that call. 

I like that the top bar remains fixed so that you can connect at any point, but as the CTA is "join us", Vs "let's get started" throughout, I think there could be a little disparity. "Join us" also feels like a bigger commitment than "Get started". I'd keep the top bar consistent and have the CTA there say "Get started" as well.

When registering, I'd make the text selectable as well. For example, you don't need to click on the little circle to select each option, but just the word, eg female or male. 

For age and location, I'd have a drop-down selector, it's standard form behaviour and what you'd expect. It also stops you from having confusion as people write things differently or in their own language, eg Deutschland instead of Germany. 

I think having the numbers 1, 2, 3 prefilled in the preference list is a little confusing, as it feels like they're already ranked. I'd have a selector beside each one for you to input the rank, as well as give an option for "Don't mind / No Preference". Some people genuinely won't mind, and it creates a barrier if they have to fill in something that doesn't feel applicable to them. 

The form is quite long to fill out, and even includes a bio, that you have to be prepared to fill out on the spot on your phone. I think you're going to struggle a lot with conversion rate. And this final page, there isn't much guidance - what length and details do you expect in the bio? What special requirements are you considering? Is that specifically accessibility requirements, or also to do with time of day preferences and the like? 

My suggestion would be to keep the sign up form very quick and simple - just name, email address, and location (also you don't necessarily need both the location and the time stamp, you could have time stamp only appear if the visitor is from a country with multiple time zones). Basically, make it as easy as possible for them to do the basic registry. Once registered, then have a follow up email which encourages them to fill out the additional details in order to be paired. Also be clear on what this information is used for - I wondered, for example, why you needed my gender. It could be that this is an important part of your algorithm, but give people a reason to know this in order to proceed. 

If they abandon a form, you've lost them forever. If they complete the form and then abandon the additional information, you still have their details registered to continue the conversation.

Or have you thought about running an AB test? It would probably be difficult at first because to be reliable you'd need to have a minimum of 1000 conversions to each variant, which would take a while to get to, but something to consider for the future. I'm a big fan of making decisions based on data. 

Very small thing - after registering, I'd cut the middle paragraph in the "thank you" section to make it shorter so that they see the social links sooner. Then, I would also put the social links horizontally rather than vertically so that you can see them all right away.

**Comment by Rob1Paul** [comment]
Joel - Masters Student - University of Liverpool. Has used Audrey.

-First of all, the colours are very nice and make the reader relaxed. Same goes for the animations. I would extend the lower colour all the way up the page as the white background at top looks a little plain. 

-The red ‘get started’ button almost entirely disappears into a thin slip of colour. 
-The ‘as seen on’ section feels a little out of place in the middle of the page, perhaps would fit better at the bottom
-On this note, I reckon having ‘recent reading partners’ as a timed slideshow-esque thing nearer the top of the page would serve more purpose. On this note, I personally would find photos of real people more engaging than the cartoon images used, but I recognise that it might not work with the website theme. 

re: sign up form

-the colour / formatting of the Grey ‘3. your bio’ square is a little clunky visually when you’re on the first page of the form ‘basic details’. Otherwise, it’s a short and concise form which is ideal
-What’s the point of having the final questions about abridged books?? It might just be worth having abridged works as a separate entity all by themselves rather than an optional thing.

feel free to call at some point if you’re unsure about anything I’ve said.

**Comment by Rob1Paul** [comment]
**Seymour | Accoutant | Age 44 | Has used Audrey.** 

Easy to scroll through. Clearly signposted. Like the green sticky menu bar. Not sure about the red large font. Like the name and logo. Buttons a nice size. UI icons express concept well. Pale green background works well with the alternate white.

Sign-up form seems good to me. Only thing I would say is that people often don't want to do much more than enter their name & email address. Getting them to tell their story might be harder to do than asking them to click through a few options that elicit their socio-economic status. Or you could ask them if they're okay with a totally random pairing to save them time.
